### ISSUE TITLE
[TypeScript] Missing triggeredByTask property

### ISSUE THREAD

**Issue by kamyker** [PlayFab/SDKGenerator#595]
File: [CloudScript.d.ts.ejs](https://github.com/PlayFab/SDKGenerator/blob/master/targets/SdkTestingCloudScript/source/Scripts/typings/PlayFab/CloudScript.d.ts.ejs)

Interface `IPlayFabContext` doesn't have `triggeredByTask` property.

Example context run from Scheduled Task:
```
{
    "playerProfile":null,
    "playStreamEvent":null,
    "triggeredByTask":{"Name":"Weekly","Id":"A80CA6D1A029A1BE"}
}
```

**Comment by toddbellMSFT** [comment]
Accepting suggestion here: https://github.com/PlayFab/SDKGenerator/pull/622
