### ISSUE TITLE
NodeJs template change is breaking existing clients. 

### ISSUE THREAD

**Issue by DSchroer** [PlayFab/SDKGenerator#689]
There was a recent change to the `package.json` template for NodeJS. This change is breaking existing applications since the index.js file is missing from recent builds.  

For visibility of the issue, it was first mentioned here:
https://github.com/PlayFab/NodeSDK/issues/105

**Comment by pgilmorepf** [comment]
Thanks for the bug report, and thanks to @lazerwalker for sending us the fix.
Release: https://github.com/PlayFab/NodeSDK/releases/tag/2.46.200422
Release Notes: https://docs.microsoft.com/en-us/gaming/playfab/release-notes/#200422
NPM Package: https://www.npmjs.com/package/playfab-sdk
