### ISSUE TITLE
Question: Is there plans to add model support to the PythonSdk?

### ISSUE THREAD

**Issue by thetestgame** [PlayFab/SDKGenerator#717]
Currently as things sit it can be extremely confusing to work with the PythonSdk. Its almost a requirement to have the documentation open currently just to know the fields. It would be much cleaner if the PythonSdk mirrored that of the Unity library using models.

**Comment by toddbellMSFT** [comment]
This was the intentional design for initial possible compatibility issues. 

The SDK team has been notified about your feature request.
